### ISSUE TITLE
1.12.2 release?

### ISSUE THREAD

**Issue by Gillenwage** [ProPercivalalb/LaserMod#10]
Will this mod ever have a 1.12.2 release? It's been about 5 years since the last request for it was asked and I was curious to know if this iconic and classic mod will ever be ported to a newer version of Minecraft

**Comment by percivalalb** [comment]
Hi, Im sorry I won't be updating to a more recent version.
The license allows others to do so if they please

**Comment by Gillenwage** [comment]
Just say you're lazy 💀
