### ISSUE TITLE
Console spam if laser travels into at least two reflectors

### ISSUE THREAD

**Issue by Hitoyu** [ProPercivalalb/LaserMod#4]
I came across a bug some short time ago while using this mod on a server. Unfortunately, a very recreate-able bug too, on both client and server.

If I create a laser beam and pass it through one reflector, there is no console spam to speak of. If I pass it through a reflector and make the beam head into another reflector, I start seeing this on the logfile:

[12:59:54] [Server thread/INFO] [FML/]: true

Messages like that keep appearing so long as the laser is on, and turning it off causes a number of these equal to the amount of reflectors in the "circuit" minus one.

[12:59:55] [Server thread/INFO] [FML/]: false

The "true" messages occur around one or two per second for each reflector in the "circuit". The "false" messages only occur once, as the laser is turned off, but not after.

To further expand, see the below screenshot.

![2015-08-12_13 02 11](https://cloud.githubusercontent.com/assets/13764595/9223504/a268d262-40f2-11e5-8b50-e55ceeff7203.png)

Emitter sends beam into R1, which forwards that beam into R2 and so on until R5, which directs it upwards into the sky. For each reflector (minus the first initial reflector) I get one of the "true" lines on console. If the reflector is not impacted by a laser, it does not output anything,

If I stop R1 reflecting into R2, I get no console spam. If I stop R2 reflecting into R3, I get roughly one or two lines of "true" per second, and one line of "false" when I turn the laser off. If I stop R3 into R4, two/three lines of "true" per second with 2 of "false" when laser gets turned off.

I am unsure where in your code these outputs are coming from. I tried searching briefly using "true" as a keyword, and soon after "testtawe" <one of the outputs I seen in console>, but found nothing for my specific version of the mod.

On servers, bug does not occur if no players are online.

I am using LaserMod-1.7.10-v1.2.0a-universal.jar on both client and server, downloaded from your Minecraft Forum thread.
Thank you.
~Hitoyu

**Comment by Hitoyu** [comment]
Convenient to see this was ignored. Thanks for not doing anything? Really, I expected more. I might as well try fix it myself.

**Comment by ProPercivalalb** [comment]
I am sorry for not replying. Only 2 years late. If you are still using it and want to remove the output yourself, if you look up "FMLLog.info" and delete all these lines that should remove the messages. I don't really want to think about this now.
